server:
  port: 8085
spring:
  application:
    name: eureka-feign
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/

# feign开启hystrix熔断
feign:
  hystrix:
    enabled: true