server:
  port: 8084
spring:
  application:
    name: eureka-ribbon
  #向注册中心注册服务
  zipkin:
    base-url: http://127.0.0.1:8080/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
